### ISSUE TITLE
How to order

### ISSUE THREAD

**Issue by FlightControl-User** [svenpetersen1965/PET-IEEE-488-Extension#1]
Hello!

Thank you for making this!

I own a PET8032SK and i need some way to interface with its GPIB port.
Is is possible to order from you the PET converter based board?

How can I produce/order this? What is the process?

I need to have a GPIB IEEE-488 ribbon connector that connects to the PET 8032SK GPIB port. On the other side, I just need a  MALE edge IEEE-4888 output (like on the main board already). So i can attach to it an SD2PET card ... Is it possible using the riser to have a 2nd GPIB port to extend other peripherals using GPIB?

Can you please help me?

**Comment by svenpetersen1965** [comment]
So, I hope, I have understood you right... you want to connect an SD2PET to the 8032SK. The SD2PET (future) has this 2x12 edge connector and you need an adapter to the (Centronics) connector of the 8032SK. 

I have already tested it with this IEEE-488 adapter:
SK IEEE port -> IEEE 488 cable (2x Centronics connector) -> adapter with riser card -> sd2pet. It works. 

I think, I have both PCBs in my PCB box. Will check later today. 

Regards,
Sven

**Comment by FlightControl-User** [comment]
Wonderful!

Is there a way for me to easily get such an adapter and riser board somehow? I'm not really into soldering but got the equipment if I need to.

What is the easiest way for me to produce or buy such an adapter?

Sven

**Comment by FlightControl-User** [comment]
Maybe to make it faster, tell me your price if you can still make one for me too. :-)
I live in Belgium, so not far. If you live near Belgium, I could even drive and fetch it by car.

**Comment by svenpetersen1965** [comment]
You might want to contact me by email: http://www.guitarsite.de/p4.htm

**Comment by FlightControl-User** [comment]
I've sent you an email :-)
